name: Tconnect Sync
on:
  schedule:
    - cron: '*/10 * * * *' # Detta kör synkningen var 10:e minut
  workflow_dispatch: # Detta gör att du kan starta den manuellt med en knapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tconnect Sync
        uses: jwoglom/tconnectsync-action@master
        with:
          tconnect_email: ${{ secrets.TCONNECT_EMAIL }}
          tconnect_password: ${{ secrets.TCONNECT_PASSWORD }}
          ns_url: ${{ secrets.NS_URL }}
          ns_secret: ${{ secrets.NS_SECRET }}
