name: Tconnect Sync
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Vi anv√§nder en stabil version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools # Detta fixar felet "pkg_resources"
          pip install tconnectsync
      - name: Run sync
        run: tconnectsync --auto-update
        env:
          TCONNECT_EMAIL: ${{ secrets.TCONNECT_EMAIL }}
          TCONNECT_PASSWORD: ${{ secrets.TCONNECT_PASSWORD }}
          NS_URL: ${{ secrets.NS_URL }}
          NS_SECRET: ${{ secrets.NS_SECRET }}
